apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: z3budah/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: z3budah/activities
      context: activities
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: z3budah/regs
      context: regs
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: z3budah/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: z3budah/execute
      context: execute
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/***/*.ts'
            dest: .
    - image: z3budah/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.js'
            dest: .
