apiVersion: apps/v1
kind: Deployment
metadata:
  name: execute-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: execute
  template:
    metadata:
      labels:
        app: execute
    spec:
      containers:
        - name: execute
          image: z3budah/execute
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name          
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'activity'
            - name: MONGO_URI
              value: 'mongodb://execute-mongo-srv:27017/execute'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: execute-srv
spec:
  selector:
    app: execute
  ports:
    - name: execute
      protocol: TCP
      port: 3000
      targetPort: 3000
