apiVersion: apps/v1
kind: Deployment
metadata:
  name: activities-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activities
  template:
    metadata:
      labels:
        app: activities
    spec:
      containers:
        - name: activities
          image: z3budah/activities
          env:
            - name: MONGO_URI
              value: 'mongodb://activities-mongo-srv:27017/activities'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: activities-srv
spec:
  selector:
    app: activities
  ports:
    - name: activities
      protocol: TCP
      port: 3000
      targetPort: 3000
