apiVersion: apps/v1
kind: Deployment
metadata:
  name: regs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regs
  template:
    metadata:
      labels:
        app: regs
    spec:
      containers:
        - name: regs
          image: z3budah/regs
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name          
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: 'activity'
            - name: MONGO_URI
              value: 'mongodb://regs-mongo-srv:27017/regs'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: regs-srv
spec:
  selector:
    app: regs
  ports:
    - name: regs
      protocol: TCP
      port: 3000
      targetPort: 3000
